import CharacterAssetsEditor from '../extras/CharacterAssetsEditor';
import GameQuestionsEditor from '../extras/GameQuestionsEditor';
import QuizQuestionsEditor from '../extras/QuizQuestionsEditor';
import StarAssociations from '../extras/StarAssociations';
import StoryScenesEditor from '../extras/StoryScenesEditor';

import type { ColumnDef, FieldDef, FilterSpec, ResourceDef } from './types';

const AGE_GROUPS = [
  { value: 'all', label: 'All ages' },
  { value: '3-5', label: '3–5 years' },
  { value: '6-8', label: '6–8 years' },
  { value: '9-12', label: '9–12 years' },
];
const DIFFICULTY = [
  { value: 'easy', label: 'Easy' },
  { value: 'medium', label: 'Medium' },
  { value: 'hard', label: 'Hard' },
];

const star: FieldDef = { name: 'star_id', label: 'Related Star', type: 'star', nullable: true, group: 'details' };
const category = (scope: string): FieldDef => ({ name: 'category_id', label: 'Category', type: 'category', nullable: true, group: 'details', categoryScope: scope });
const age: FieldDef = { name: 'age_group', label: 'Age group', type: 'select', options: AGE_GROUPS, default: 'all', group: 'details' };
const difficulty: FieldDef = { name: 'difficulty', label: 'Difficulty', type: 'select', options: DIFFICULTY, default: 'easy', group: 'details' };
const order: FieldDef = { name: 'display_order', label: 'Display order', type: 'number', default: 0, min: 0, group: 'details', help: 'Lower numbers appear first.' };

const statusCol: ColumnDef = { key: 'status', header: 'Status', kind: 'status', width: '120px' };
const starCol: ColumnDef = { key: 'star', header: 'Star', kind: 'star', field: 'star_id' };
const categoryCol: ColumnDef = { key: 'category', header: 'Category', kind: 'category', field: 'category_id' };
const updatedCol: ColumnDef = { key: 'updated', header: 'Updated', kind: 'updated', width: '130px' };

const starFilter: FilterSpec = { key: 'star', label: 'Star', column: 'star_id', options: 'star' };
const categoryFilter: FilterSpec = { key: 'category', label: 'Category', column: 'category_id', options: 'category' };
const difficultyFilter: FilterSpec = { key: 'difficulty', label: 'Difficulty', column: 'difficulty', options: DIFFICULTY };
const ageFilter: FilterSpec = { key: 'age', label: 'Age', column: 'age_group', options: AGE_GROUPS };

export const RESOURCES: ResourceDef[] = [
  {
    key: 'stories',
    table: 'stories',
    translationType: 'story',
    label: { singular: 'Story', plural: 'Stories' },
    icon: 'book',
    description: 'Illustrated stories that teach the qualities of the 14 Stars.',
    titleField: 'title',
    slugField: 'slug',
    hasStatus: true,
    preview: 'story',
    searchFields: ['title', 'short_description'],
    categoryScope: 'story',
    defaults: { age_group: 'all', xp_reward: 25, display_order: 0 },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'short_description', label: 'Short description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'body', label: 'Full story', type: 'richtext', translatable: true, group: 'content', help: 'Each paragraph becomes one page of the story in the app.' },
      { name: 'moral', label: 'Moral / lesson', type: 'textarea', translatable: true, rows: 2, group: 'content' },
      { name: 'takeaway', label: 'Real-life takeaway', type: 'textarea', translatable: true, rows: 2, group: 'content' },
      { name: 'cover_media_id', label: 'Cover image', type: 'image', folder: 'stories', group: 'media' },
      { name: 'background_media_id', label: 'Story background', type: 'image', folder: 'stories', group: 'media' },
      { name: 'narration_media_id', label: 'Narration audio', type: 'audio', folder: 'stories', group: 'media' },
      star,
      category('story'),
      age,
      { name: 'duration_minutes', label: 'Duration (minutes)', type: 'number', min: 1, max: 120, nullable: true, group: 'details' },
      { name: 'xp_reward', label: 'XP reward', type: 'number', min: 0, max: 500, default: 25, group: 'details', help: 'XP a child earns the first time they finish the story.' },
      order,
    ],
    columns: [
      { key: 'cover', header: '', kind: 'image', field: 'cover_media_id', width: '64px' },
      { key: 'title', header: 'Title', kind: 'title' },
      starCol,
      categoryCol,
      { key: 'age', header: 'Age', kind: 'text', field: 'age_group', width: '80px' },
      statusCol,
      updatedCol,
    ],
    filters: [starFilter, categoryFilter, ageFilter],
    extras: [{ key: 'scenes', title: 'Scenes (animated story)', component: StoryScenesEditor }],
  },
  {
    key: 'duas',
    table: 'duas',
    translationType: 'dua',
    label: { singular: 'Du’a', plural: 'Du’as' },
    icon: 'heart',
    description: 'Short duas with Arabic text, translations and recitation audio.',
    titleField: 'name',
    slugField: 'slug',
    hasStatus: true,
    preview: 'dua',
    searchFields: ['name', 'transliteration', 'translation'],
    categoryScope: 'dua',
    defaults: { age_group: 'all', xp_reward: 15, display_order: 0 },
    fields: [
      { name: 'name', label: 'Du’a name', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'arabic_text', label: 'Arabic text', type: 'textarea', required: true, rtl: true, rows: 3, group: 'content' },
      { name: 'transliteration', label: 'Transliteration', type: 'textarea', rows: 2, group: 'content' },
      { name: 'translation', label: 'Translation', type: 'textarea', translatable: true, rows: 3, group: 'content', help: 'Enter the English text on the default tab; use the language tabs for Urdu and Farsi translations.' },
      { name: 'explanation', label: 'Short explanation', type: 'textarea', translatable: true, rows: 2, group: 'content' },
      { name: 'audio_media_id', label: 'Recitation audio', type: 'audio', folder: 'duas', group: 'media' },
      { name: 'cover_media_id', label: 'Cover image', type: 'image', folder: 'duas', group: 'media' },
      star,
      category('dua'),
      age,
      { name: 'xp_reward', label: 'XP reward', type: 'number', min: 0, max: 500, default: 15, group: 'details' },
      order,
    ],
    columns: [
      { key: 'cover', header: '', kind: 'image', field: 'cover_media_id', width: '64px' },
      { key: 'title', header: 'Name', kind: 'title' },
      { key: 'audio', header: 'Audio', kind: 'audio', field: 'audio_media_id', width: '170px' },
      starCol,
      categoryCol,
      statusCol,
      updatedCol,
    ],
    filters: [starFilter, categoryFilter, ageFilter],
  },
  {
    key: 'games',
    table: 'games',
    translationType: 'game',
    label: { singular: 'Game', plural: 'Games' },
    icon: 'game',
    description: 'Game content and configuration. The game engine itself lives in the app.',
    titleField: 'name',
    slugField: 'slug',
    hasStatus: true,
    preview: 'game',
    searchFields: ['name', 'description'],
    categoryScope: 'game',
    defaults: { game_type: 'multiple_choice', difficulty: 'easy', age_group: 'all', reward_points: 50, reward_stars: 0, display_order: 0, config: {} },
    fields: [
      { name: 'name', label: 'Game name', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'instructions', label: 'Instructions', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'quality', label: 'Quality / teaching', type: 'textarea', translatable: true, rows: 2, group: 'content', help: 'The character quality this game teaches.' },
      { name: 'thumbnail_media_id', label: 'Thumbnail', type: 'image', folder: 'games', group: 'media' },
      { name: 'background_media_id', label: 'Background', type: 'image', folder: 'games', group: 'media' },
      { name: 'sound_media_id', label: 'Sound effects', type: 'audio', folder: 'games', group: 'media' },
      {
        name: 'game_type',
        label: 'Game type',
        type: 'select',
        required: true,
        group: 'details',
        default: 'multiple_choice',
        options: [
          { value: 'multiple_choice', label: 'Multiple choice' },
          { value: 'true_false', label: 'True / False' },
          { value: 'quiz', label: 'Quiz' },
          { value: 'story_choice', label: 'Story choice' },
          { value: 'good_deed_challenge', label: 'Good deed challenge' },
          { value: 'matching', label: 'Matching' },
          { value: 'memory', label: 'Memory' },
          { value: 'drag_drop', label: 'Drag & drop (sorting)' },
          { value: 'sequence', label: 'Sequence (put in order)' },
        ],
      },
      difficulty,
      age,
      star,
      category('game'),
      { name: 'reward_points', label: 'Reward points (XP)', type: 'number', min: 0, max: 500, default: 50, group: 'details' },
      { name: 'reward_stars', label: 'Reward stars', type: 'number', min: 0, max: 14, default: 0, group: 'details' },
      order,
    ],
    columns: [
      { key: 'thumb', header: '', kind: 'image', field: 'thumbnail_media_id', width: '64px' },
      { key: 'title', header: 'Name', kind: 'title' },
      { key: 'type', header: 'Type', kind: 'badge', field: 'game_type', width: '150px' },
      { key: 'difficulty', header: 'Difficulty', kind: 'text', field: 'difficulty', width: '100px' },
      starCol,
      statusCol,
      updatedCol,
    ],
    filters: [
      starFilter,
      categoryFilter,
      difficultyFilter,
      {
        key: 'type',
        label: 'Type',
        column: 'game_type',
        options: [
          { value: 'multiple_choice', label: 'Multiple choice' },
          { value: 'true_false', label: 'True / False' },
          { value: 'quiz', label: 'Quiz' },
          { value: 'story_choice', label: 'Story choice' },
          { value: 'good_deed_challenge', label: 'Good deed challenge' },
          { value: 'matching', label: 'Matching' },
          { value: 'memory', label: 'Memory' },
          { value: 'drag_drop', label: 'Drag & drop' },
          { value: 'sequence', label: 'Sequence' },
        ],
      },
    ],
    extras: [{ key: 'questions', title: 'Game content', component: GameQuestionsEditor }],
  },
  {
    key: 'daily-star',
    table: 'daily_stars',
    translationType: 'daily_star',
    label: { singular: 'Daily Star', plural: 'Daily Stars' },
    icon: 'sparkles',
    description: 'Schedule a Daily Star for any date.',
    titleField: 'title',
    hasStatus: true,
    preview: 'daily',
    searchFields: ['title', 'short_story'],
    defaultSort: 'newest',
    defaults: {},
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'short_story', label: 'Short story', type: 'richtext', translatable: true, group: 'content' },
      { name: 'lesson', label: 'Lesson', type: 'textarea', translatable: true, rows: 2, group: 'content' },
      { name: 'takeaway', label: 'Real-life takeaway', type: 'textarea', translatable: true, rows: 2, group: 'content' },
      { name: 'cover_media_id', label: 'Image', type: 'image', folder: 'stories', group: 'media' },
      { name: 'audio_media_id', label: 'Audio', type: 'audio', folder: 'stories', group: 'media' },
      { name: 'scheduled_date', label: 'Date', type: 'date', required: true, group: 'details' },
      { ...star, label: 'Star' },
      { name: 'duration_minutes', label: 'Duration (minutes)', type: 'number', min: 1, max: 60, nullable: true, group: 'details' },
      { name: 'scene_data', label: 'Animation / scene data (JSON)', type: 'json', group: 'details', help: 'Optional. Structured scene configuration for the animated player.', default: {} },
    ],
    columns: [
      { key: 'date', header: 'Date', kind: 'date', field: 'scheduled_date', width: '130px' },
      { key: 'title', header: 'Title', kind: 'title' },
      starCol,
      statusCol,
      updatedCol,
    ],
    filters: [starFilter],
  },
  {
    key: 'quizzes',
    table: 'quizzes',
    translationType: 'quiz',
    label: { singular: 'Quiz', plural: 'Quizzes' },
    icon: 'help',
    description: 'Quizzes made of multiple-choice and true/false questions.',
    titleField: 'title',
    slugField: 'slug',
    hasStatus: true,
    preview: 'quiz',
    searchFields: ['title', 'description'],
    categoryScope: 'quiz',
    defaults: { difficulty: 'easy', points_per_question: 10, passing_score: 60, is_daily: false },
    fields: [
      { name: 'title', label: 'Quiz title', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      difficulty,
      star,
      category('quiz'),
      { name: 'points_per_question', label: 'Points per question', type: 'number', min: 0, max: 100, default: 10, group: 'details' },
      { name: 'passing_score', label: 'Passing score (%)', type: 'number', min: 0, max: 100, default: 60, group: 'details' },
      { name: 'time_limit_seconds', label: 'Time limit (seconds)', type: 'number', min: 10, nullable: true, group: 'details', help: 'Leave empty for no time limit.' },
      { name: 'questions_per_attempt', label: 'Questions per attempt', type: 'number', min: 1, nullable: true, group: 'details', help: 'Leave empty to ask every question.' },
      { name: 'is_daily', label: 'Daily quiz', type: 'boolean', default: false, group: 'details' },
    ],
    columns: [
      { key: 'title', header: 'Title', kind: 'title' },
      { key: 'difficulty', header: 'Difficulty', kind: 'text', field: 'difficulty', width: '100px' },
      { key: 'daily', header: 'Daily', kind: 'yesno', field: 'is_daily', width: '80px' },
      starCol,
      statusCol,
      updatedCol,
    ],
    filters: [starFilter, categoryFilter, difficultyFilter],
    extras: [{ key: 'questions', title: 'Questions', component: QuizQuestionsEditor }],
  },
  {
    key: 'good-deeds',
    table: 'good_deeds',
    translationType: 'good_deed',
    label: { singular: 'Good Deed', plural: 'Good Deeds' },
    icon: 'heart',
    description: 'Simple kind actions children can do every day.',
    titleField: 'title',
    hasStatus: true,
    preview: 'deed',
    searchFields: ['title', 'description'],
    categoryScope: 'good_deed',
    defaults: { difficulty: 'easy', points: 5, age_group: 'all', display_order: 0 },
    fields: [
      { name: 'title', label: 'Good deed', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'icon_emoji', label: 'Icon (emoji)', type: 'emoji', group: 'media', help: 'Shown when no icon image is set.' },
      { name: 'icon_media_id', label: 'Icon / image', type: 'image', folder: 'general', group: 'media' },
      star,
      category('good_deed'),
      difficulty,
      { name: 'points', label: 'Points / reward', type: 'number', min: 0, max: 100, default: 5, group: 'details' },
      age,
      order,
    ],
    columns: [
      { key: 'icon', header: '', kind: 'image', field: 'icon_media_id', width: '64px' },
      { key: 'title', header: 'Good deed', kind: 'title' },
      starCol,
      categoryCol,
      { key: 'points', header: 'Points', kind: 'number', field: 'points', width: '80px' },
      statusCol,
      updatedCol,
    ],
    filters: [starFilter, categoryFilter, difficultyFilter, ageFilter],
  },
  {
    key: 'reflections',
    table: 'reflections',
    translationType: 'reflection',
    label: { singular: 'Reflection', plural: 'Reflections' },
    icon: 'chat',
    description: 'Prompts that invite children to think and reflect.',
    titleField: 'question',
    hasStatus: true,
    preview: 'reflection',
    searchFields: ['question', 'description'],
    categoryScope: 'reflection',
    defaults: { age_group: 'all', display_order: 0 },
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'image_media_id', label: 'Image', type: 'image', folder: 'general', group: 'media' },
      { name: 'audio_media_id', label: 'Audio', type: 'audio', folder: 'general', group: 'media' },
      star,
      category('reflection'),
      age,
      order,
    ],
    columns: [
      { key: 'image', header: '', kind: 'image', field: 'image_media_id', width: '64px' },
      { key: 'title', header: 'Question', kind: 'title' },
      starCol,
      { key: 'age', header: 'Age', kind: 'text', field: 'age_group', width: '80px' },
      statusCol,
      updatedCol,
    ],
    filters: [starFilter, categoryFilter, ageFilter],
  },
  {
    key: 'wisdom',
    table: 'wisdom',
    translationType: 'wisdom',
    label: { singular: 'Wisdom', plural: 'Wisdom' },
    icon: 'bulb',
    description: 'Quotes and sayings exactly as you provide them — nothing is generated.',
    titleField: 'title',
    hasStatus: true,
    preview: 'wisdom',
    searchFields: ['title', 'wisdom_text', 'translation'],
    categoryScope: 'wisdom',
    defaults: { display_order: 0 },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'wisdom_text', label: 'Wisdom text', type: 'textarea', required: true, translatable: true, rows: 4, group: 'content' },
      { name: 'arabic_text', label: 'Arabic text (optional)', type: 'textarea', rtl: true, rows: 3, group: 'content' },
      { name: 'translation', label: 'Translation', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'explanation', label: 'Explanation', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'image_media_id', label: 'Image', type: 'image', folder: 'general', group: 'media' },
      { name: 'audio_media_id', label: 'Audio', type: 'audio', folder: 'general', group: 'media' },
      star,
      category('wisdom'),
      order,
    ],
    columns: [
      { key: 'image', header: '', kind: 'image', field: 'image_media_id', width: '64px' },
      { key: 'title', header: 'Title', kind: 'title' },
      starCol,
      categoryCol,
      statusCol,
      updatedCol,
    ],
    filters: [starFilter, categoryFilter],
  },
  {
    key: 'audio',
    table: 'audio',
    translationType: 'audio',
    label: { singular: 'Audio', plural: 'Audio' },
    icon: 'music',
    description: 'Narration, dua recitations, character voices, music and sound effects.',
    titleField: 'name',
    hasStatus: true,
    preview: 'audio',
    searchFields: ['name', 'description'],
    categoryScope: 'audio',
    syncFromMedia: { field: 'media_id', durationField: 'duration_seconds', nameField: 'name' },
    defaults: { audio_type: 'story_narration', display_order: 0 },
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'media_id', label: 'Audio file', type: 'audio', required: true, folder: 'audio', group: 'media' },
      { name: 'thumbnail_media_id', label: 'Thumbnail', type: 'image', folder: 'general', group: 'media' },
      {
        name: 'audio_type',
        label: 'Type',
        type: 'select',
        required: true,
        group: 'details',
        default: 'story_narration',
        options: [
          { value: 'story_narration', label: 'Story narration' },
          { value: 'dua', label: 'Du’a audio' },
          { value: 'character_voice', label: 'Character voice' },
          { value: 'game_sound', label: 'Game sound' },
          { value: 'background_music', label: 'Background music' },
          { value: 'sound_effect', label: 'Sound effect' },
        ],
      },
      { name: 'language_code', label: 'Language', type: 'language', nullable: true, group: 'details' },
      { name: 'story_id', label: 'Related story', type: 'story', nullable: true, group: 'details' },
      star,
      category('audio'),
      { name: 'duration_seconds', label: 'Duration (seconds)', type: 'number', readOnly: true, nullable: true, group: 'details', help: 'Filled in automatically from the file.' },
      order,
    ],
    columns: [
      { key: 'title', header: 'Name', kind: 'title' },
      { key: 'audio', header: 'Preview', kind: 'audio', field: 'media_id', width: '200px' },
      { key: 'file', header: 'File', kind: 'audio-meta', field: 'media_id', width: '170px' },
      { key: 'type', header: 'Type', kind: 'badge', field: 'audio_type', width: '150px' },
      { key: 'lang', header: 'Language', kind: 'language', field: 'language_code', width: '90px' },
      statusCol,
      updatedCol,
    ],
    filters: [
      starFilter,
      { key: 'language', label: 'Language', column: 'language_code', options: 'language' },
      {
        key: 'type',
        label: 'Type',
        column: 'audio_type',
        options: [
          { value: 'story_narration', label: 'Story narration' },
          { value: 'dua', label: 'Du’a audio' },
          { value: 'character_voice', label: 'Character voice' },
          { value: 'game_sound', label: 'Game sound' },
          { value: 'background_music', label: 'Background music' },
          { value: 'sound_effect', label: 'Sound effect' },
        ],
      },
    ],
  },
  {
    key: 'characters',
    table: 'characters',
    translationType: 'character',
    label: { singular: 'Character', plural: 'Characters' },
    icon: 'happy',
    description: 'Fictional child characters (for example Ali and Sakina) — never sacred personalities.',
    titleField: 'name',
    slugField: 'slug',
    hasStatus: false,
    toggleField: 'is_active',
    preview: 'character',
    searchFields: ['name', 'description'],
    defaultSort: 'order',
    defaults: { gender: 'boy', is_active: true, display_order: 0 },
    fields: [
      { name: 'name', label: 'Character name', type: 'text', required: true, group: 'content' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 3, group: 'content' },
      { name: 'main_media_id', label: 'Main image', type: 'image', folder: 'characters', group: 'media' },
      { name: 'talking_media_id', label: 'Talking image / asset', type: 'media', kinds: ['image', 'animation'], folder: 'characters', group: 'media' },
      { name: 'happy_media_id', label: 'Happy expression', type: 'image', folder: 'characters', group: 'media' },
      { name: 'sad_media_id', label: 'Sad expression', type: 'image', folder: 'characters', group: 'media' },
      { name: 'thinking_media_id', label: 'Thinking expression', type: 'image', folder: 'characters', group: 'media' },
      { name: 'surprised_media_id', label: 'Surprised expression', type: 'image', folder: 'characters', group: 'media' },
      { name: 'talking_animation_media_id', label: 'Talking animation', type: 'media', kinds: ['animation', 'video'], folder: 'characters', group: 'media' },
      { name: 'idle_animation_media_id', label: 'Idle animation', type: 'media', kinds: ['animation', 'video'], folder: 'characters', group: 'media' },
      { name: 'voice_media_id', label: 'Voice', type: 'audio', folder: 'characters', group: 'media', help: 'Default voice line. Per-situation lines (welcome, story, dua…) are added under “Extra assets”.' },
      {
        name: 'gender',
        label: 'Gender',
        type: 'select',
        required: true,
        group: 'details',
        default: 'boy',
        options: [
          { value: 'boy', label: 'Boy' },
          { value: 'girl', label: 'Girl' },
        ],
      },
      { name: 'language_code', label: 'Language', type: 'language', nullable: true, group: 'details' },
      { name: 'is_active', label: 'Active', type: 'boolean', default: true, group: 'details' },
      order,
    ],
    columns: [
      { key: 'img', header: '', kind: 'image', field: 'main_media_id', width: '64px' },
      { key: 'title', header: 'Name', kind: 'title' },
      { key: 'gender', header: 'Gender', kind: 'badge', field: 'gender', width: '100px' },
      { key: 'lang', header: 'Language', kind: 'language', field: 'language_code', width: '90px' },
      { key: 'active', header: 'Active', kind: 'toggle', field: 'is_active', width: '90px' },
      updatedCol,
    ],
    filters: [
      {
        key: 'gender',
        label: 'Gender',
        column: 'gender',
        options: [
          { value: 'boy', label: 'Boy' },
          { value: 'girl', label: 'Girl' },
        ],
      },
    ],
    extras: [{ key: 'assets', title: 'Extra assets (voice lines, animations…)', component: CharacterAssetsEditor }],
  },
  {
    key: 'categories',
    table: 'categories',
    translationType: 'category',
    label: { singular: 'Category', plural: 'Categories' },
    icon: 'tags',
    description: 'Categories shared by stories, duas, games, good deeds, reflections, wisdom and audio.',
    titleField: 'name',
    slugField: 'slug',
    hasStatus: false,
    toggleField: 'is_enabled',
    orderable: true,
    defaultSort: 'order',
    preview: 'generic',
    searchFields: ['name'],
    defaults: { is_enabled: true, display_order: 0, scopes: ['story', 'dua', 'game', 'good_deed', 'reflection', 'wisdom', 'audio', 'quiz'] },
    fields: [
      { name: 'name', label: 'Category name', type: 'text', required: true, translatable: true, group: 'content' },
      {
        name: 'scopes',
        label: 'Used for',
        type: 'multiselect',
        group: 'details',
        options: [
          { value: 'story', label: 'Stories' },
          { value: 'dua', label: 'Du’as' },
          { value: 'game', label: 'Games' },
          { value: 'quiz', label: 'Quizzes' },
          { value: 'good_deed', label: 'Good deeds' },
          { value: 'reflection', label: 'Reflections' },
          { value: 'wisdom', label: 'Wisdom' },
          { value: 'audio', label: 'Audio' },
        ],
      },
      { name: 'is_enabled', label: 'Enabled', type: 'boolean', default: true, group: 'details' },
      order,
    ],
    columns: [
      { key: 'title', header: 'Name', kind: 'title' },
      { key: 'scopes', header: 'Used for', kind: 'text', field: 'scopes' },
      { key: 'enabled', header: 'Enabled', kind: 'toggle', field: 'is_enabled', width: '100px' },
      { key: 'order', header: 'Order', kind: 'number', field: 'display_order', width: '80px' },
    ],
    filters: [],
  },
  {
    key: 'stars',
    table: 'stars',
    translationType: 'star',
    label: { singular: 'Star', plural: 'Stars' },
    icon: 'star',
    description: 'The 14 Stars.',
    titleField: 'name',
    hasStatus: true,
    fixedSet: true,
    preview: 'star',
    searchFields: ['name', 'title'],
    defaultSort: 'order',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, translatable: true, group: 'content' },
      { name: 'title', label: 'Title / honorific', type: 'text', translatable: true, group: 'content', help: 'Shown beneath the name.' },
      { name: 'description', label: 'Description', type: 'textarea', translatable: true, rows: 4, group: 'content' },
      { name: 'qualities', label: 'Qualities / teachings', type: 'textarea', translatable: true, rows: 4, group: 'content', help: 'One quality per line. The first line is the Star’s headline lesson.' },
      { name: 'image_media_id', label: 'Image', type: 'image', folder: 'stars', group: 'media', help: 'Symbolic artwork only — never a figurative depiction of the Ma’sumeen.' },
      { name: 'background_media_id', label: 'Background', type: 'image', folder: 'stars', group: 'media' },
      { name: 'number', label: 'Number', type: 'number', readOnly: true, group: 'details' },
    ],
    columns: [
      { key: 'image', header: '', kind: 'image', field: 'image_media_id', width: '64px' },
      { key: 'number', header: '#', kind: 'number', field: 'number', width: '50px' },
      { key: 'title', header: 'Name', kind: 'title' },
      statusCol,
      updatedCol,
    ],
    filters: [],
    extras: [{ key: 'associations', title: 'Associated content', component: StarAssociations }],
  },
];

export const RESOURCE_BY_KEY: Record<string, ResourceDef> = Object.fromEntries(RESOURCES.map((r) => [r.key, r]));
