// Generates supabase/seed.sql from the content that is bundled in the app (src/data), so that
// the existing stories, duas, quiz questions and the 14 Stars can be managed from the CMS.
//
//   node supabase/tools/generate-seed.mjs
//
// The output is idempotent (ON CONFLICT DO NOTHING) — re-running the seed never overwrites edits.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), '14stars-seed-'));
const entry = path.join(tmp, 'entry.ts');
const bundle = path.join(tmp, 'bundle.cjs');
fs.writeFileSync(
  entry,
  `export * from ${JSON.stringify(path.join(root, 'src/data/index.ts').replace(/\\/g, '/'))};
   export { KINDNESS_MISSIONS } from ${JSON.stringify(path.join(root, 'src/data/games/kindnessMissions.ts').replace(/\\/g, '/'))};`
);
await build({
  entryPoints: [entry],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  outfile: bundle,
  alias: { '@': path.join(root, 'src') },
  logLevel: 'error',
});
const { createRequire } = await import('node:module');
const { STARS, STORIES, DUAS, QUIZ_QUESTIONS } = createRequire(import.meta.url)(bundle);

const s = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const starRef = (n) => `(select id from public.stars where number = ${n})`;
const catRef = (slug) => `(select id from public.categories where slug = ${s(slug)} and deleted_at is null)`;

const out = [];
out.push('-- GENERATED by supabase/tools/generate-seed.mjs — do not edit by hand.');
out.push('-- Safe to run repeatedly: every insert is ON CONFLICT DO NOTHING.\n');

out.push(`insert into public.languages (code, name, native_name, direction, is_default, sort_order) values
  ('en', 'English', 'English', 'ltr', true, 0),
  ('ur', 'Urdu', 'اردو', 'rtl', false, 1),
  ('fa', 'Farsi', 'فارسی', 'rtl', false, 2)
on conflict (code) do nothing;\n`);

const categories = [
  ['kindness', 'Kindness'], ['honesty', 'Honesty'], ['patience', 'Patience'], ['generosity', 'Generosity'],
  ['knowledge', 'Knowledge'], ['courage', 'Courage'], ['worship', 'Worship'],
  ['daily', 'Daily'], ['food', 'Food'], ['sleep', 'Sleep'], ['family', 'Family'], ['learning', 'Learning'],
];
out.push('insert into public.categories (slug, name, display_order) values');
out.push(categories.map(([slug, name], i) => `  (${s(slug)}, ${s(name)}, ${i})`).join(',\n'));
out.push('on conflict (slug) where deleted_at is null do nothing;\n');

out.push(`insert into public.app_settings (key, value, is_public) values
  ('app_config', '{"app_name": "14 Stars", "support_email": "", "maintenance_mode": false}', true),
  ('upload_limits', '{"image_mb": 10, "audio_mb": 50, "animation_mb": 20, "video_mb": 50}', false),
  ('publishing', '{"confirm_before_publish": true, "default_status": "draft"}', false)
on conflict (key) do nothing;\n`);

out.push(`insert into public.characters (slug, name, gender, description, language_code, is_active, display_order) values
  ('ali', 'Ali', 'boy', 'A friendly fictional boy who calls to remind boys about their learning time.', 'en', true, 0),
  ('sakina', 'Sakina', 'girl', 'A friendly fictional girl who calls to remind girls about their learning time.', 'en', true, 1)
on conflict (slug) do nothing;\n`);

out.push('insert into public.stars (number, slug, name, title, description, qualities, status, display_order) values');
out.push(
  STARS.map(
    (st) =>
      `  (${st.id}, ${s('star-' + st.id)}, ${s(st.name)}, ${s(st.honorific)}, ${s(st.lessonSummary)}, ${s(st.lessonTitle)}, 'published', ${st.id})`
  ).join(',\n')
);
out.push('on conflict (number) do nothing;\n');

const storyCategory = { 1: 'kindness', 2: 'courage', 3: 'generosity' };
STORIES.forEach((st, i) => {
  const extras = {
    cover_emoji: st.coverEmoji,
    gradient: st.gradient,
    difficulty: st.difficulty,
    pages: st.pages.map((p) => ({ emoji: p.emoji, gradient: p.gradient })),
    sequence_events: st.sequenceEvents,
    quiz: st.quiz,
    moral_choice: st.moral,
    badge_emoji: st.badgeEmoji,
    badge_title: st.badgeTitle,
  };
  out.push(
    `insert into public.stories (slug, title, short_description, body, moral, star_id, category_id, age_group, duration_minutes, xp_reward, extras, status, display_order) values (${s(st.id)}, ${s(st.title)}, ${s(st.summary)}, ${s(st.pages.map((p) => p.text).join('\n\n'))}, ${s(st.moral.options[st.moral.correctIndex])}, ${starRef(st.relatedStarId)}, ${catRef(storyCategory[st.relatedStarId] ?? 'kindness')}, 'all', ${st.minutes}, ${st.xpReward}, ${j(extras)}, 'published', ${i}) on conflict (slug) where deleted_at is null do nothing;`
  );
});
out.push('');

DUAS.forEach((d, i) => {
  const extras = {
    repeat_segments: d.repeatSegments,
    arabic_segments: d.arabicSegments,
    meaning_emoji: d.meaningEmoji,
    concept_emojis: d.conceptEmojis,
    concept_labels: d.conceptLabels,
  };
  out.push(
    `insert into public.duas (slug, name, arabic_text, transliteration, translation, explanation, category_id, age_group, xp_reward, extras, status, display_order) values (${s(d.id)}, ${s(d.title)}, ${s(d.arabic)}, ${s(d.transliteration)}, ${s(d.translation)}, ${s(d.meaningExplainer)}, ${catRef(d.category)}, 'all', ${d.xpReward}, ${j(extras)}, 'published', ${i}) on conflict (slug) where deleted_at is null do nothing;`
  );
});
out.push('');

out.push(
  `insert into public.quizzes (slug, title, description, difficulty, points_per_question, passing_score, status, display_order) values ('general-knowledge', 'General Knowledge', 'Questions about the 14 Stars and everyday good habits.', 'easy', 10, 60, 'published', 0) on conflict (slug) where deleted_at is null do nothing;`
);
QUIZ_QUESTIONS.forEach((q, i) => {
  out.push(
    `insert into public.quiz_questions (quiz_id, sort_order, question_type, prompt, options, correct_index, explanation, points) select z.id, ${i}, 'multiple_choice', ${s(q.question)}, ${j(q.options)}, ${q.correctIndex}, ${s(q.explanation)}, ${q.xpReward} from public.quizzes z where z.slug = 'general-knowledge' and not exists (select 1 from public.quiz_questions x where x.quiz_id = z.id and x.sort_order = ${i});`
  );
});

const file = path.join(root, 'supabase/seed.sql');
fs.writeFileSync(file, out.join('\n') + '\n');
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`wrote ${path.relative(root, file)} (${STARS.length} stars, ${STORIES.length} stories, ${DUAS.length} duas, ${QUIZ_QUESTIONS.length} quiz questions)`);
