import type { IconType } from 'react-icons';
import {
  IoAlertCircle,
  IoAdd,
  IoArrowBack,
  IoArrowDown,
  IoArrowUp,
  IoBook,
  IoCalendar,
  IoCheckmarkCircle,
  IoChevronBack,
  IoChevronDown,
  IoChevronForward,
  IoClose,
  IoCloudUpload,
  IoCopy,
  IoCreate,
  IoDocumentText,
  IoEye,
  IoEyeOff,
  IoFlash,
  IoFolderOpen,
  IoGameController,
  IoGlobe,
  IoGrid,
  IoHardwareChip,
  IoHeart,
  IoHelpCircle,
  IoImage,
  IoInformationCircle,
  IoLanguage,
  IoLibrary,
  IoLockClosed,
  IoLogOut,
  IoMenu,
  IoMusicalNotes,
  IoPause,
  IoPeople,
  IoPlay,
  IoPricetags,
  IoRefresh,
  IoSearch,
  IoSettings,
  IoSparkles,
  IoStar,
  IoSwapHorizontal,
  IoTime,
  IoTrash,
  IoVideocam,
  IoBulb,
  IoChatbubbles,
  IoHappy,
  IoFilm,
  IoRibbon,
  IoPulse,
  IoDownload,
} from 'react-icons/io5';

const ICONS = {
  add: IoAdd,
  alert: IoAlertCircle,
  'arrow-back': IoArrowBack,
  down: IoArrowDown,
  up: IoArrowUp,
  book: IoBook,
  calendar: IoCalendar,
  'check-circle': IoCheckmarkCircle,
  'chevron-left': IoChevronBack,
  'chevron-down': IoChevronDown,
  'chevron-right': IoChevronForward,
  close: IoClose,
  upload: IoCloudUpload,
  copy: IoCopy,
  edit: IoCreate,
  doc: IoDocumentText,
  eye: IoEye,
  'eye-off': IoEyeOff,
  flash: IoFlash,
  folder: IoFolderOpen,
  game: IoGameController,
  globe: IoGlobe,
  grid: IoGrid,
  chip: IoHardwareChip,
  heart: IoHeart,
  help: IoHelpCircle,
  image: IoImage,
  info: IoInformationCircle,
  language: IoLanguage,
  library: IoLibrary,
  lock: IoLockClosed,
  logout: IoLogOut,
  menu: IoMenu,
  music: IoMusicalNotes,
  pause: IoPause,
  people: IoPeople,
  play: IoPlay,
  tags: IoPricetags,
  refresh: IoRefresh,
  search: IoSearch,
  settings: IoSettings,
  sparkles: IoSparkles,
  star: IoStar,
  swap: IoSwapHorizontal,
  time: IoTime,
  trash: IoTrash,
  video: IoVideocam,
  bulb: IoBulb,
  chat: IoChatbubbles,
  happy: IoHappy,
  film: IoFilm,
  ribbon: IoRibbon,
  pulse: IoPulse,
  download: IoDownload,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 18, className }: { name: IconName; size?: number; className?: string }) {
  const Cmp = ICONS[name];
  return <Cmp size={size} className={className} aria-hidden="true" />;
}
